name: DCBot
version: 1.0.0
description: DirectCode Plugin for PolymorphicBot
dependencies:
  github:
    git: git://github.com/DirectMyFile/github.dart.git
  http: '>=0.11.0'
  http_server: '>=0.9.3 <0.10.0'
  irc: '>=1.4.5 <1.4.9'
  polymorphic_bot:
    path: ../../../PolymorphicBot/
  route: '>=0.4.6 <0.5.0'
plugin:
  commands:
    help:
      description: Provides Help Information
    commands:
      description: Lists Commands for Each Plugin
    dart-version:
      description: Provides Dart Version Information
      usage: dart-version [channel]
    reload:
      description: Reloads Plugins
