name: DCBot
version: 1.0.0
description: DirectCode Plugin for PolymorphicBot
dependencies:
  github: any
  http: '>=0.11.0'
  http_server: '>=0.9.3 <0.10.0'
  irc: '>=1.4.5 <1.4.9'
  neo:
    git: http://git.directcode.org/neo/tools.git
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
  route: '>=0.4.6 <0.5.0'
plugin:
  commands:
    help:
      description: Provides Help Information
    commands:
      description: Lists Commands for Each Plugin
    dart-version:
      description: Provides Dart Version Information
      usage: [channel]
    reload:
      description: Reloads Plugins
      usage: ""
    command:
      usage: <command>
      description: Gives Command Information
    stop:
      usage: ""
      description: Stops the Bot