name: DCBot
version: 1.0.0
description: DirectCode Plugin for PolymorphicBot
dependencies:
  github: '>=2.0.0 <3.0.0'
  http: '>=0.11.0'
  irc: '>=2.0.0 <3.0.0'
  neo:
    git: http://git.directcode.org/neo/tools.git
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
  dslink:
    git:
      url: https://github.com/IOT-DSA/sdk-dslink-dart.git
      ref: 3c30e98f73d85d073bf343d58ffc5ff198aba8b0
plugin:
  commands:
    help:
      description: Provides Help Information
    commands:
      description: Lists Commands for Each Plugin
    dart-version:
      description: Provides Dart Version Information
      usage:
      - channel
    command:
      usage: <command>
      description: Gives Command Information
    stop:
      usage: ''
      description: Stops the Bot
dependency_overrides:
  console:
    git: https://github.com/DirectMyFile/console.dart.git
  http: ">=0.11.1+1 <0.12.0"
