name: DCBot
version: 1.0.0
description: DirectCode Plugin for PolymorphicBot
dependencies:
  github: any
  http: '>=0.11.0'
  irc: '>=2.0.0 <3.0.0'
  neo:
    git: http://git.directcode.org/neo/tools.git
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
plugin:
  commands:
    help:
      description: Provides Help Information
    commands:
      description: Lists Commands for Each Plugin
    dart-version:
      description: Provides Dart Version Information
      usage:
      - channel
    command:
      usage: <command>
      description: Gives Command Information
    stop:
      usage: ''
      description: Stops the Bot
